//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalTransparency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailSetting
    {
        public string Id { get; set; }
        public string FromEmail { get; set; }
        public string FromName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ServerHost { get; set; }
        public Nullable<int> ServerPort { get; set; }
        public bool SSL { get; set; }
        public bool SRA { get; set; }
    }
}
