//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalTransparency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuIcon
    {
        public int Id { get; set; }
        public string IconClass { get; set; }
        public string DisplayHTML { get; set; }
    }
}
